name: Crowdin Pull Request

#on:
#  schedule:
#    - cron: '0 */1 * * *' # Every hour - https://crontab.guru/#0_*/1_*_*_*

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: 'l10n_1.20.4'

          create_pull_request: true
          pull_request_title: 'Update translations from Crowdin'
          pull_request_body: ''
          pull_request_base_branch_name: '1.20.4'
          commit_message: 'Update translations from Crowdin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}